package com.gamestore.entity;
// Generated 6 May, 2020 9:30:56 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * Review generated by hbm2java
 */
@Entity
@Table(name = "review", catalog = "gamestoredb")
@NamedQueries({
	@NamedQuery(name= "Review.listAll", query="SELECT r FROM Review r ORDER BY r.reviewTime DESC"),
	@NamedQuery(name= "Review.countAll", query="SELECT COUNT(r) FROM Review r"),
	@NamedQuery(name= "Review.findByCustomerAndGame",
			query= "SELECT r FROM Review r WHERE r.customer.customerId =:customerId" 
					+ " AND r.game.gameId =:gameId")
})
public class Review implements java.io.Serializable {

	private int reviewId;
	private Customer customer;
	private Game game;
	private int rating;
	private String headline;
	private String comment;
	private Date reviewTime;

	public Review() {
	}

	public Review(int reviewId, Customer customer, Game game, int rating, String headline, String comment,
			Date reviewTime) {
		this.reviewId = reviewId;
		this.customer = customer;
		this.game = game;
		this.rating = rating;
		this.headline = headline;
		this.comment = comment;
		this.reviewTime = reviewTime;
	}

	@Id
	@Column(name = "review_id")
	@GeneratedValue(strategy = GenerationType.IDENTITY )
	public int getReviewId() {
		return this.reviewId;
	}

	public void setReviewId(int reviewId) {
		this.reviewId = reviewId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "customer_id", nullable = false)
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "game_id", nullable = false)
	public Game getGame() {
		return this.game;
	}

	public void setGame(Game game) {
		this.game = game;
	}

	@Column(name = "rating", nullable = false)
	public int getRating() {
		return this.rating;
	}

	public void setRating(int rating) {
		this.rating = rating;
	}

	@Column(name = "headline", nullable = false, length = 128)
	public String getHeadline() {
		return this.headline;
	}

	public void setHeadline(String headline) {
		this.headline = headline;
	}

	@Column(name = "comment", nullable = false, length = 500)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "review_time", nullable = false, length = 19)
	public Date getReviewTime() {
		return this.reviewTime;
	}

	public void setReviewTime(Date reviewTime) {
		this.reviewTime = reviewTime;
	}
	
	@Transient
	public String getStars() {
		String result="";
		
		int numberOfStarsOn = (int) rating;
		
		for(int i=1;i<= numberOfStarsOn;i++) {
			result+="on,";
		}
		for(int i=numberOfStarsOn+1;i<=5;i++) {
			result+="off,";
		}
		
		return result.substring(0, result.length()-1);
	}

}
